### ISSUE TITLE
Can't use plugin – unclear how mediamtx.yml is created or what format is required

### ISSUE THREAD

**Issue by modeitsch** [midoelhawy/mediamtx-node-client#1]
Hi, thank you for this useful project!

I'm trying to test the mediamtx-node-client plugin but I’m currently stuck because I don’t understand how the mediamtx.yml file is being created or what format it’s expected to follow.

Right now, I’m unable to use the plugin properly. Could you please clarify:

Does the plugin generate the mediamtx.yml file automatically, or do I need to create it manually?

If it's manual, could you provide an example or schema of the correct YAML format to use?

Are there any required fields or conventions specific to this plugin?

I’d really like to test it out, but this step is blocking me.

Thanks in advance!

**Comment by midoelhawy** [comment]
Hi @modeitsch,
thanks for your interest!

The `mediamtx-node-client` plugin allows you to interact with the MediaMTX API to dynamically create, update, and delete streaming paths.

By default, the plugin does **not** generate a `mediamtx.yml` file unless you explicitly enable the persistent configuration feature via `persistentMediaMtxConfig`.

---

### Example 1 – Single YAML file (simple setup)

This saves both the **global configuration** and the **stream paths** in one file.

#### Client setup:

```ts
const mediaMtxClient = new MediamtxNodeClient({
  baseURL: "http://mymediamtxserver:9997/", // MediaMTX API base URL
  playbackServerBaseURL: "http://mymediamtxserver:9996/", // Public playback base URL
  auth: {
    username: "user", // API username
    password: "-01",  // API password
  },
  persistentMediaMtxConfig: {
    saveAsUniqueFile: true,              // Save both global + paths config in a single YAML file
    saveGlobalConfig: true,              // Save the global MediaMTX settings
    savePathsConfig: true,               // Save stream paths
    outputFilePath: "/etc/mediamtx.yml", // Path to the output YAML file
    ignoreRpiCamera: true,               // Exclude Raspberry Pi camera entries
  }
});
```

#### Docker Compose:

```yaml
mediamtx:
  image: bluenviron/mediamtx
  volumes:
    - ./mediamtx.yml:/etc/mediamtx.yml
  command: ["/mediamtx", "/etc/mediamtx.yml"]
```

 Make sure the `outputFilePath` is the **same file** MediaMTX reads as config at startup.

---

###  Example 2 – Split config (global + paths in separate files)

This setup separates the **global configuration** and **stream paths** into two files, and merges them before MediaMTX starts.

#### Client setup:

```ts
const mediaMtxClient = new MediamtxNodeClient({
  baseURL: "http://mymediamtxserver:9997/",
  playbackServerBaseURL: "http://mymediamtxserver:9996/",
  auth: {
    username: "user",
    password: "-01",
  },
  persistentMediaMtxConfig: {
    saveAsUniqueFile: false, // Don't combine configs into one file
    saveGlobalConfig: true,  // Save global settings separately
    savePathsConfig: true,   // Save stream paths separately
    globalConfigOutputFilePath: "/manager/globalConfig.yml", // Global config file path
    pathsOutputFilePath: "/manager/streamConfig.yml",        // Paths config file path
    ignoreRpiCamera: true,
  }
});
```

#### Docker Compose:

```yaml
mediamtx:
  image: bluenviron/mediamtx
  volumes:
    - ./base-mediamtx-config.yml:/base-mediamtx-config.yml
    - /manager/globalConfig.yml:/globalConfig.yml
    - /manager/streamConfig.yml:/streamConfig.yml
    - ./mediamtxEntryPointOverwrite.sh:/mediamtxEntryPointOverwrite.sh:ro
  entrypoint: ["/bin/sh", "/mediamtxEntryPointOverwrite.sh"]
```

#### `mediamtxEntryPointOverwrite.sh`:

```sh
echo "Start merging Configs"
cat /globalConfig.yml > /mediamtx.yml
echo "" >> /mediamtx.yml
cat /streamConfig.yml >> /mediamtx.yml
echo "" >> /mediamtx.yml
cat /base-mediamtx-config.yml >> /mediamtx.yml
echo "" >> /mediamtx.yml

echo "Merging config ok!!"
cat /mediamtx.yml

echo "Starting mediamtx"
/mediamtx /mediamtx.yml
```

This gives you full flexibility:

* base config is static
* stream paths are dynamically updated
* global settings are persisted when changed through the API

---

### How persistence works

Every time the client makes a change via the API (create/update/delete a stream or patch global config), the library regenerates and saves the updated YAML config — either to a single file or to separate files, depending on your setup.

---

**NOTE**:
Whether you use a single or multiple files, ensure that the merged result is passed to MediaMTX at startup.
If the file MediaMTX uses is not the same one the client writes to (or not properly merged), changes won’t take effect.

Let me know if you'd like a sample output YAML!
